 export const CardActionTyps={
    HIDDEN_SHOW_CARD_DROPDOWN : 'HIDDEN_SHOW_CARD_DROPDOWN',
    ADD_TO_SHOP :'ADD_TO_SHOP',
    ADD_SHOP_CARD_QUANTITY : "ADD_SHOP_CARD_QUANTITY",
    MINUS_SHOP_CARD_QUANTITY : "MINUS_SHOP_CARD_QUANTITY",
    REMOVE_SHOP_ITEM : "REMOVE_SHOP_ITEM"
};
